version: '3.2'
services:
  r:
    container_name: 'biomage-worker-r'
    build:
      context: r/
      target: dev
    volumes:
      - ./r:/r:cached
    expose:
      - "4000"

  python:
    container_name: 'biomage-worker-python'
    build:
      context: python/
      target: dev
    volumes:
      - ./python:/python:cached
