kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: worker-storage
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2