apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-config
  namespace: {{.Release.Namespace}}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
data:
  r: "{{ .Values.r.image }}"
  python: "{{ .Values.python.image }}"
  ignoreTimeout: "{{ .Values.ignoreTimeout }}"